/**
 * export-from-db.mjs — ดึงเนื้อหาคอร์ส gas-mastery จาก Supabase ออกมาเป็นไฟล์ SQL
 * เก็บลง course-content/module-XX/lesson-X.Y.sql (idempotent · re-runnable)
 * = backup เนื้อหาที่ version-control ได้ + เอาไป re-apply ลง DB อื่นได้
 *
 * วิธีรัน (ต้องตั้ง env ก่อน — ดูชื่อใน lib/supabase.js):
 *   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... node course-content/export-from-db.mjs
 *
 * ผลลัพธ์:
 *   course-content/_modules.sql              ← course_modules ทุกแถว
 *   course-content/module-00/lesson-0.1.sql  ← ลง lessons ทีละบท
 *   course-content/module-12/lesson-12.4.sql
 */
import { createClient } from '@supabase/supabase-js';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SLUG = 'gas-mastery';
const HERE = path.dirname(fileURLToPath(import.meta.url));

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error('✗ ต้องตั้ง env: SUPABASE_URL และ SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}
const db = createClient(url, key, { auth: { autoRefreshToken: false, persistSession: false } });

// ── helpers: เขียนค่าเป็น SQL literal โดยไม่ต้อง escape เอง ──
function dollar(value) {
  const s = value == null ? '' : String(value);
  let tag = 'T';
  while (s.includes('$' + tag + '$')) tag += 'x'; // เลี่ยงตัวคั่นชนเนื้อหา
  return `$${tag}$${s}$${tag}$`;
}
function jsonbLit(value) {
  const s = JSON.stringify(value ?? []);
  let tag = 'J';
  while (s.includes('$' + tag + '$')) tag += 'x';
  return `$${tag}$${s}$${tag}$::jsonb`;
}
function intOrNull(v) {
  return v == null || v === '' ? 'NULL' : String(parseInt(v, 10));
}
const pad2 = (n) => String(n).padStart(2, '0');

async function main() {
  const { data: course, error: cErr } = await db
    .from('courses').select('id, slug, title').eq('slug', SLUG).single();
  if (cErr || !course) throw new Error('ไม่พบคอร์ส slug=' + SLUG + ' : ' + (cErr && cErr.message));

  const { data: modules } = await db
    .from('course_modules').select('*').eq('course_id', course.id).order('sort_order');
  const { data: lessons } = await db
    .from('lessons').select('*').eq('course_id', course.id);

  const moduleById = new Map(modules.map((m) => [m.id, m]));

  // _modules.sql
  const modSql = [
    '-- =============================================',
    `-- course_modules — ${course.title} (${SLUG})`,
    '-- idempotent · ON CONFLICT (id) DO UPDATE',
    '-- generated by export-from-db.mjs',
    '-- =============================================',
    '',
    ...modules.map((m) =>
      `INSERT INTO course_modules (id, course_id, sort_order, title, description)\n` +
      `VALUES (${dollar(m.id)}::uuid, ${dollar(m.course_id)}::uuid, ${m.sort_order}, ${dollar(m.title)}, ${dollar(m.description)})\n` +
      `ON CONFLICT (id) DO UPDATE SET\n` +
      `  sort_order = EXCLUDED.sort_order, title = EXCLUDED.title,\n` +
      `  description = EXCLUDED.description, updated_at = now();\n`
    ),
  ].join('\n');
  await writeFile(path.join(HERE, '_modules.sql'), modSql, 'utf8');

  // lessons → ทีละไฟล์
  let count = 0;
  for (const l of lessons) {
    const m = moduleById.get(l.module_id);
    const mo = m ? m.sort_order : 99;
    const dir = path.join(HERE, `module-${pad2(mo)}`);
    await mkdir(dir, { recursive: true });

    const sql =
      '-- =============================================\n' +
      `-- Lesson ${mo}.${l.sort_order} — ${l.title}\n` +
      `-- Module ${mo} · Position ${l.sort_order}` +
      `${l.is_free_preview ? ' · Free preview' : ''}${l.is_published ? ' · Published' : ' · Draft'}` +
      `${l.is_core ? ' · Core' : ''}${l.is_quick_path ? ' · Quick path' : ''}\n` +
      '-- idempotent · ON CONFLICT (id) DO UPDATE · generated by export-from-db.mjs\n' +
      '-- =============================================\n\n' +
      'INSERT INTO lessons (\n' +
      '  id, module_id, course_id, sort_order, title, summary,\n' +
      '  content_md, code_snippets, quiz, image_urls,\n' +
      '  estimated_minutes, is_free_preview, is_published, is_core, is_quick_path\n' +
      ') VALUES (\n' +
      `  ${dollar(l.id)}::uuid, ${dollar(l.module_id)}::uuid, ${dollar(l.course_id)}::uuid, ${l.sort_order},\n` +
      `  ${dollar(l.title)}, ${dollar(l.summary)},\n` +
      `  ${dollar(l.content_md)},\n` +
      `  ${jsonbLit(l.code_snippets)},\n` +
      `  ${jsonbLit(l.quiz)},\n` +
      `  ${jsonbLit(l.image_urls)},\n` +
      `  ${intOrNull(l.estimated_minutes)}, ${!!l.is_free_preview}, ${!!l.is_published}, ${!!l.is_core}, ${!!l.is_quick_path}\n` +
      ') ON CONFLICT (id) DO UPDATE SET\n' +
      '  module_id = EXCLUDED.module_id, sort_order = EXCLUDED.sort_order,\n' +
      '  title = EXCLUDED.title, summary = EXCLUDED.summary,\n' +
      '  content_md = EXCLUDED.content_md, code_snippets = EXCLUDED.code_snippets,\n' +
      '  quiz = EXCLUDED.quiz, image_urls = EXCLUDED.image_urls,\n' +
      '  estimated_minutes = EXCLUDED.estimated_minutes,\n' +
      '  is_free_preview = EXCLUDED.is_free_preview, is_published = EXCLUDED.is_published,\n' +
      '  is_core = EXCLUDED.is_core, is_quick_path = EXCLUDED.is_quick_path,\n' +
      '  updated_at = now();\n';

    await writeFile(path.join(dir, `lesson-${mo}.${l.sort_order}.sql`), sql, 'utf8');
    count++;
  }

  console.log(`✓ export เสร็จ: ${modules.length} modules, ${count} lessons → course-content/`);
}

main().catch((e) => { console.error('✗', e.message); process.exit(1); });
